# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands



# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

start-at-login = true

# See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
accordion-padding = 50

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'horizontal'

# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse window-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace --focus-follows-window T'

# 'main' binding mode must be always presented
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.main.binding]
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-b = 'workspace B'
alt-c = 'workspace C'
alt-o = 'workspace O'
alt-p = 'workspace P'
alt-s = 'workspace S'
alt-t = 'workspace T'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace --focus-follows-window 1'
alt-shift-2 = 'move-node-to-workspace --focus-follows-window 2'
alt-shift-3 = 'move-node-to-workspace --focus-follows-window 3'
alt-shift-4 = 'move-node-to-workspace --focus-follows-window 4'
alt-shift-5 = 'move-node-to-workspace --focus-follows-window 5'
alt-shift-6 = 'move-node-to-workspace --focus-follows-window 6'
alt-shift-7 = 'move-node-to-workspace --focus-follows-window 7'
alt-shift-8 = 'move-node-to-workspace --focus-follows-window 8'
alt-shift-9 = 'move-node-to-workspace --focus-follows-window 9'
alt-shift-b = 'move-node-to-workspace --focus-follows-window B'
alt-shift-c = 'move-node-to-workspace --focus-follows-window C'
alt-shift-o = 'move-node-to-workspace --focus-follows-window O'
alt-shift-p = 'move-node-to-workspace --focus-follows-window P'
alt-shift-s = 'move-node-to-workspace --focus-follows-window S'
alt-shift-t = 'move-node-to-workspace --focus-follows-window T'

# See: https://nikitabobko.github.io/AeroSpace/commands#summon-workspace
alt-cmd-1 = 'summon-workspace 1'
alt-cmd-2 = 'summon-workspace 2'
alt-cmd-3 = 'summon-workspace 3'
alt-cmd-4 = 'summon-workspace 4'
alt-cmd-5 = 'summon-workspace 5'
alt-cmd-6 = 'summon-workspace 6'
alt-cmd-7 = 'summon-workspace 7'
alt-cmd-8 = 'summon-workspace 8'
alt-cmd-9 = 'summon-workspace 9'
alt-cmd-b = 'summon-workspace B'
alt-cmd-c = 'summon-workspace C'
alt-cmd-o = 'summon-workspace O'
alt-cmd-p = 'summon-workspace P'
alt-cmd-s = 'summon-workspace S'
alt-cmd-t = 'summon-workspace T'

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
alt-enter = 'exec-and-forget open -n /Applications/WezTerm.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'
alt-e = 'mode aerospace'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

[mode.aerospace.binding]
esc = 'mode main'
r = 'mode resize'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
h = ['focus left', 'mode main']
j = ['focus down', 'mode main']
k = ['focus up', 'mode main']
l = ['focus right', 'mode main']
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
f = ['fullscreen', 'mode main']

# See: https://nikitabobko.github.io/AeroSpace/commands#split
# backwards from logic??
backslash = ['split horizontal', 'mode main']
minus = ['split vertical', 'mode main']

# See: https://nikitabobko.github.io/AeroSpace/commands#balance-sizes
equal = ['balance-sizes', 'mode main']

# See: https://nikitabobko.github.io/AeroSpace/commands#close
x = ['close', 'mode main']

# See: https://nikitabobko.github.io/AeroSpace/commands#move
shift-h = ['move left', 'mode main']
shift-j = ['move down', 'mode main']
shift-k = ['move up', 'mode main']
shift-l = ['move right', 'mode main']
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#join-with
ctrl-h = ['join-with left', 'mode main']
ctrl-j = ['join-with down', 'mode main']
ctrl-k = ['join-with up', 'mode main']
ctrl-l = ['join-with right', 'mode main']

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
i = ['layout v_accordion', 'mode main']
u = ['layout h_accordion', 'mode main']
e = ['layout tiles horizontal vertical', 'mode main']
shift-space = ['layout floating tiling', 'mode main']

[mode.resize.binding]
esc = 'mode main'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
minus = 'resize smart -50'
equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#balance-sizes
shift-equal = ['balance-sizes', 'mode main']
